[package]
name = "recisdb-rust"
version = "0.1.0"
authors = ["kazuki"]
edition = "2021"
description = "Recisdb-rs can read both Unix chardev-based and BonDriver-based TV sources. "
rust-version = "1.56"

[dependencies]
futures = { git="https://github.com/kazuki0824/futures-rs.git" , branch="asyncio_abortable_2"}
clap = {version = "~2.33.3", features = ["yaml"]}
fancy-regex = "0.7.1"
b25-sys = {path = "../b25-sys"}
ctrlc = { version = ">=3.0", features = ["termination"] }
nix = ">0.19.0"
libloading = ">=0.7.0"
cpp_utils = "0.3.0"
cfg-if = ">=1.0.0"

[build-dependencies]
cc = ">=1.0.70"
bindgen = ">=0.59.1"
glob = "0.3"

[package.metadata.deb]
maintainer = "Kazuki Kuroda <kazukuro0824+dev@gmail.com>"
copyright = "2021, Kazuki Kuroda  <kazukuro0824+dev@gmail.com>"
license-file = ["LICENSE", "4"]
extended-description = """\
A simple command for ISDB-T character device.
Recisdb-rs can read both Unix chardev-based and BonDriver-based TV sources. """
depends = "libpcsclite1, $auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/cargo-deb", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/cargo-deb/README", "644"],
]